openapi: 3.0.3
info:
  title: Q2A API
  description: "The plugin adds simple API to serve some data as JSON. Here is documentation for endpoints. Currently plugin supports user authentication only via Q2A session mechanism."
  contact:
    name: GitHub issues
    url: https://github.com/awaluk/q2a-api/issues
  license:
    name: MIT
    url: https://github.com/awaluk/q2a-api/blob/master/LICENSE
  version: 0.2.0

externalDocs:
  description: GitHub repository
  url: https://github.com/awaluk/q2a-api

servers:
  - url: /api

tags:
  - name: Auth
  - name: Account
  - name: Category
  - name: General

paths:
  /login:
    post:
      tags:
        - Auth
      summary: User login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - login
                - password
              properties:
                login:
                  type: string
                  example: user
                  description: User email or name (when logging in via name is enabled)
                password:
                  type: string
                  example: pass
                rememberMe:
                  type: boolean
                  example: false
                  default: false
      responses:
        200:
          description: User logged
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDto"
        400:
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  fields:
                    type: object
                    properties:
                      password:
                        type: object
                        example: Wrong password
        403:
          description: Already logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Already logged in

  /account:
    get:
      tags:
        - Account
      summary: Get logged in user data
      operationId: getAccountData
      security:
        - q2aSession: []
      responses:
        200:
          description: User data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDto"
        401:
          description: Unauthorized

  /favourites:
    get:
      tags:
        - Account
      summary: Get favourite items for logged in user
      operationId: getAccountFavourites
      security:
        - q2aSession: []
      responses:
        200:
          description: User favourite items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FavouritesDto"
        401:
          description: Unauthorized

  /categories:
    get:
      tags:
        - Category
      summary: Get list of categories
      operationId: getCategoriesList
      responses:
        200:
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryDto"

  /statistics:
    get:
      tags:
        - General
      summary: Get some general statistics
      description: "4 counters: questions, answers, comments, users"
      operationId: getStatistics
      responses:
        200:
          description: Statistics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatisticsDto"

components:
  schemas:
    UserLevelDto:
      type: integer
      enum: [0, 10, 20, 50, 80, 100, 120]
      description: >
        Defines the user role/function:
          - `0` - no role, standard user
          - `10` - approved user (only when users approval is enabled in Q2A)
          - `20` - expert
          - `50` - editor
          - `80` - moderator
          - `100` - admin
          - `120` - super admin

    AccountDto:
      type: object
      required:
        - id
        - name
        - email
        - level
        - points
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: user1
          description: "Username"
        email:
          type: string
          example: "user1@example.com"
        level:
          $ref: "#/components/schemas/UserLevelDto"
        points:
          type: integer
          example: 200

    StatisticsDto:
      type: object
      required:
        - questionsCount
        - answersCount
        - commentsCount
        - usersCount
      properties:
        questionsCount:
          type: integer
          example: 5
        answersCount:
          type: integer
          example: 7
        commentsCount:
          type: integer
          example: 3
        usersCount:
          type: integer
          example: 6

    CategoryDto:
      required:
        - id
        - title
        - slug
        - path
        - description
        - subcategories
        - questionsCount
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Category 1"
        slug:
          type: string
          example: "category-1"
        path:
          type: string
          example: "category-1"
        description:
          type: string
          example: "Category description"
        position:
          type: integer
          example: 1
        questionsCount:
          type: integer
          example: 3
        subcategories:
          type: array
          items:
            $ref: "#/components/schemas/CategoryDto"

    FavouritesDto:
      type: object
      required:
        - questions
        - users
        - tags
        - categories
      properties:
        questions:
          type: array
          description: "Array of favourite questions"
          items:
            type: integer
            example: 1
            description: User id
        users:
          type: array
          description: "Array of favourite users"
          items:
            type: string
            example: user1
            description: User handle (username)
        tags:
          type: array
          description: "Array of favourite tags"
          items:
            type: string
            example: "tag-1"
            description: "Tag name"
        categories:
          type: array
          description: "Array of favourite categories"
          items:
            type: string
            example: "Category 1"
            description: "Category name"

  securitySchemes:
    q2aSession:
      type: apiKey
      in: cookie
      name: PHPSESSID
